// Mapping of city names to IATA airport codes
export const cityToIataMap: Record<string, string> = {
  // South Asia
  dhaka: "DAC",
  dacca: "DAC",
  sylhet: "ZYL",
  mumbai: "BOM",
  bombay: "BOM",
  delhi: "DEL",
  "new delhi": "DEL",
  bangalore: "BLR",
  kolkata: "CCU",
  calcutta: "CCU",
  hyderabad: "HYD",
  lahore: "LHE",
  karachi: "KHI",
  islamabad: "ISB",
  rawalpindi: "ISB",
  chandigarh: "IXC",
  jaipur: "JAI",
  lucknow: "LKO",
  ahmedabad: "AMD",
  surat: "STV",
  pune: "PNQ",
  goa: "GOI",
  panaji: "GOI",
  kochi: "COK",
  cochin: "COK",
  trivandrum: "TRV",
  thiruvananthapuram: "TRV",
  indore: "IDR",
  bhopal: "BHO",
  nagpur: "NAG",
  nashik: "ISK",

  // Middle East
  dubai: "DXB",
  abudhabi: "AUH",
  "abu dhabi": "AUH",
  qatar: "DOH",
  doha: "DOH",
  riyadh: "RIY",
  jeddah: "JED",
  beirut: "BEY",
  istanbul: "IST",

  // Europe
  london: "LHR",
  paris: "CDG",
  berlin: "BER",
  frankfurt: "FRA",
  amsterdam: "AMS",
  zurich: "ZRH",
  geneva: "GVA",
  rome: "FCO",
  milan: "MXP",
  barcelona: "BCN",
  madrid: "MAD",
  lisbon: "LIS",
  vienna: "VIE",
  prague: "PRG",
  budapest: "BUD",
  warsaw: "WAW",
  stockholm: "ARN",
  copenhagen: "CPH",

  // North America
  newyork: "JFK",
  "new york": "JFK",
  losangeles: "LAX",
  "los angeles": "LAX",
  chicago: "ORD",
  dallas: "DFW",
  houston: "IAH",
  sanfrancisco: "SFO",
  "san francisco": "SFO",
  seattle: "SEA",
  denver: "DEN",
  boston: "BOS",
  atlanta: "ATL",
  miami: "MIA",
  toronto: "YYZ",
  vancouver: "YVR",
  mexico: "MEX",
  mexicocity: "MEX",
  "mexico city": "MEX",
  montreal: "YUL",
  calgary: "YYC",
  ottawa: "YOW",
  quebec: "YQB",
  edmonton: "YEG",
  halifax: "YHZ",

  // Asia Pacific
  bangkok: "BKK",
  singapore: "SIN",
  kualalumpur: "KUL",
  "kuala lumpur": "KUL",
  hongkong: "HKG",
  "hong kong": "HKG",
  shanghai: "SHA",
  beijing: "PEI",
  tokyo: "NRT",
  seoul: "ICN",
  sydney: "SYD",
  melbourne: "MEL",
  auckland: "AKL",
  wellington: "WLG",
  perth: "PER",

  // Middle East
  manama: "BAH",
  muscat: "MCT",
  salalah: "SLL",
  almaty: "ALA",
  astana: "NQZ",
};

export function convertCityToIata(cityName: string): string {
  const normalized = cityName.toLowerCase().trim();
  return cityToIataMap[normalized] || cityName.toUpperCase();
}
